<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>

    <Version>2.2.1</Version>
    <Authors>Nodirbek Abdulaxadov</Authors>
    <Company>MDevs Group</Company>
    <PackageProjectUrl>https://github.com/Nodirbek-Abdulaxadov/LiteAPI</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Nodirbek-Abdulaxadov/LiteAPI</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

</Project>
